{'lr': 0.0122542857,
'data': 'FMNIST', 
'gamma': 0.9, 
'B_scaling': 0.05, 
'algorithm': 'PEPITA', 
'drop_rate': 0.1, 
'batch_size': 64, 
'num_epochs': 100, 
'num_seeds': 5, 
'train_mode': 'adversarial', 
'hidden_size': 1024, 
'optimizer_name': 'mom', 
'double_precision': True, 
'adv_eps': 0.1,
'with_bias': True,
'adversarial_attacks': ['pgd', 'fgsm'], 
'training_adversarial_attack': 'pgd',
'save_performances_values': True,
'activation_function': 'relu',
'noisy_gradients': False,
'mean_noisy_gradients': 0.0,
'stddev_noisy_gradients': 1.0}